@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Fri Jan 20 13:01:41 +0100 2023
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto a86e12bd0c094377865af8884db30294 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot TB_SwitchMultistadio_behav xil_defaultlib.TB_SwitchMultistadio -log elaborate.log"
call xelab  -wto a86e12bd0c094377865af8884db30294 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot TB_SwitchMultistadio_behav xil_defaultlib.TB_SwitchMultistadio -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
