webtalk_init -webtalk_dir C:/Users/rosariaritacanale/Documents/progetto/Esercizio10_switchMultistadio/Esercizio10_switchMultistadio.sim/sim_1/behav/xsim/xsim.dir/TB_SwitchMultistadio_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Jan 21 11:09:49 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ef3ac7a1-bd19-4e77-8140-d7cf0e1c2948" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a86e12bd0c094377865af8884db30294" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "13" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1800 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "3.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "50 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.12_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6424_KB" -context "xsim\\usage"
webtalk_transmit -clientid 637819910 -regid "" -xml C:/Users/rosariaritacanale/Documents/progetto/Esercizio10_switchMultistadio/Esercizio10_switchMultistadio.sim/sim_1/behav/xsim/xsim.dir/TB_SwitchMultistadio_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/rosariaritacanale/Documents/progetto/Esercizio10_switchMultistadio/Esercizio10_switchMultistadio.sim/sim_1/behav/xsim/xsim.dir/TB_SwitchMultistadio_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/rosariaritacanale/Documents/progetto/Esercizio10_switchMultistadio/Esercizio10_switchMultistadio.sim/sim_1/behav/xsim/xsim.dir/TB_SwitchMultistadio_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
